//Aqui um banco de dados simples que fiz para meu TCC.

CREATE DATABASE banco;
GO
 
CREATE TABLE PLANO(
	ID INT IDENTITY PRIMARY KEY,
	NOME VARCHAR (100) NOT NULL,
	VALOR VARCHAR(200) NOT NULL,
	DESCRICAO VARCHAR(900) NOT NULL,
	COD_STATUS CHAR(1) NULL,
	)
GO
 
CREATE TABLE EMPRESA(
	ID INT IDENTITY PRIMARY KEY,
	NOME VARCHAR(200) NOT NULL,
	TELEFONE VARCHAR(14) NOT NULL,
	CNPJ VARCHAR(12) NOT NULL,
	ENDERECO VARCHAR(500) NOT NULL,
	COD_STATUS CHAR(1) NULL,
    PLANO_ID  INT NOT NULL, 
FOREIGN KEY (PLANO_ID) REFERENCES PLANO (ID),
)
GO

CREATE TABLE USUARIO(
    ID INT IDENTITY PRIMARY KEY,
	NOME VARCHAR(600) NOT NULL,
	EMAIL VARCHAR(700) NOT NULL,
	SENHA VARCHAR(200) NOT NULL,
	COD_STATUS CHAR(1) NULL,
	EMPRESA_ID INT NOT NULL,
FOREIGN KEY (EMPRESA_ID) REFERENCES EMPRESA (ID),
)
GO

CREATE TABLE AGENDAMENTO(
    ID INT IDENTITY PRIMARY KEY,
	DIA VARCHAR(10) NOT NULL,
	HORA VARCHAR(5) NOT NULL,
	DESCRICAO VARCHAR(600) NOT NULL,
	COD_STATUS CHAR(1) NULL,
	EMPRESA_ID INT NOT NULL,
	USUARIO_ID INT NOT NULL,
FOREIGN KEY (USUARIO_ID) REFERENCES USUARIO (ID),
FOREIGN KEY (EMPRESA_ID) REFERENCES EMPRESA (ID),
)
GO
